export type LocalePage = {
  slug: string;
  htmlLang: string;
  dir?: "rtl";
  title: string;
  description: string;
  eyebrow: string;
  headline: string;
  lead: string;
  download: string;
  trust: string[];
  features: Array<{ title: string; body: string }>;
  versionUpdate: { label: string; title: string; body: string };
  closing: string;
};

export const localePages: LocalePage[] = [
  {
    slug: "zh-hant", htmlLang: "zh-Hant", title: "GuitarTool｜調音器、節拍器與和弦庫", description: "全部練習功能均免費，核心工具可離線使用；僅可選完整視覺主題付費，單套一次購買永久解鎖。", eyebrow: "專注練習所需的一切", headline: "核心調音、跟拍與和弦工具，離線也能使用。", lead: "GuitarTool 把即時調音器、彈性節拍器與吉他／烏克麗麗和弦庫放在同一個安靜、清楚的練習流程中。", download: "在 App Store 免費下載", trust: ["核心工具離線", "無廣告", "無需帳戶"], versionUpdate: { label: "1.0.12 版本更新", title: "五套完整主題，讓整套練習介面換一種性格。", body: "App 的全部練習功能均免費；僅可選完整視覺主題為付費內容。主題展廳新增五套付費完整主題，可在購買前逐頁預覽；每套為獨立的一次性 App Store 內購，永久解鎖、無訂閱，下載後可離線使用，後續將持續推出新主題。" }, closing: "拿起樂器就能開始，不讓工具打斷練習。",
    features: [{ title: "即時調音器", body: "支援多種吉他調弦、High-G／Low-G GCEA 與半音階模式，顯示音分、頻率、輸入強度及穩定度。" }, { title: "彈性節拍器", body: "20–500 BPM、1–12 拍、TAP 測速、細分、Swing、計時器及漸進加速，並支援後置閃光燈節拍（全部主拍／僅重音、三檔強度）。" }, { title: "雙樂器和弦庫", body: "吉他與烏克麗麗各有 855 個名稱，共 19,244 個指法；可切換、編輯、辨識及試聽，並把目前指法卡片儲存或分享。" }],
  },
  {
    slug: "es", htmlLang: "es", title: "GuitarTool | Afinador, metrónomo y acordes", description: "Todas las funciones de práctica son gratis. Solo los temas visuales opcionales son de pago y se desbloquean para siempre con una compra única.", eyebrow: "TODO PARA UNA PRÁCTICA CONCENTRADA", headline: "Afina, marca el pulso y encuentra acordes sin conexión.", lead: "GuitarTool reúne un afinador en tiempo real, un metrónomo flexible y bibliotecas profundas de acordes de guitarra y ukelele en una sola aplicación tranquila y clara.", download: "Descargar gratis en App Store", trust: ["Funciones esenciales sin conexión", "Sin anuncios", "Sin cuenta"], versionUpdate: { label: "NOVEDADES DE LA VERSIÓN 1.0.12", title: "Cinco temas premium transforman toda la experiencia.", body: "Todas las funciones de práctica son gratis; solo los temas visuales completos opcionales son de pago. Previsualiza cada tema en todas las pantallas antes de comprarlo. Cada uno es una compra única independiente en App Store, con desbloqueo permanente y sin suscripción; funciona sin conexión tras descargarlo y se añadirán más temas." }, closing: "Abre la aplicación, toma el instrumento y empieza a practicar.",
    features: [{ title: "Afinador en tiempo real", body: "Afinaciones estándar, Drop D, DADGAD, abiertas, GCEA y modo cromático, con cents, frecuencia, intensidad y estabilidad." }, { title: "Metrónomo flexible", body: "20–500 BPM, de 1 a 12 pulsos, Tap Tempo, subdivisiones, swing, temporizadores y aumento progresivo del tempo. El flash trasero puede marcar todos los pulsos principales o solo los acentos con tres intensidades." }, { title: "Acordes interactivos", body: "855 nombres para cada instrumento y 19.244 digitaciones en total; cambia, edita, identifica y escucha posiciones, y guarda o comparte la tarjeta actual." }],
  },
  {
    slug: "pt-br", htmlLang: "pt-BR", title: "GuitarTool | Afinador, metrônomo e acordes", description: "Todos os recursos de prática são grátis. Apenas os temas visuais opcionais são pagos e desbloqueados para sempre com compra única.", eyebrow: "TUDO PARA UMA PRÁTICA FOCADA", headline: "Afine, mantenha o tempo e encontre acordes offline.", lead: "O GuitarTool reúne afinador em tempo real, metrônomo flexível e bibliotecas completas de acordes de guitarra e ukulele em um fluxo simples e tranquilo.", download: "Baixar grátis na App Store", trust: ["Recursos essenciais offline", "Sem anúncios", "Sem conta"], versionUpdate: { label: "NOVIDADES DA VERSÃO 1.0.12", title: "Cinco temas premium transformam toda a experiência.", body: "Todos os recursos de prática são grátis; apenas os temas visuais completos opcionais são pagos. Veja cada tema em todas as telas antes de comprar. Cada um é uma compra única separada na App Store, com desbloqueio permanente e sem assinatura; funciona offline após baixar e novos temas serão adicionados." }, closing: "Pegue o instrumento e comece: a ferramenta fica em segundo plano.",
    features: [{ title: "Afinador em tempo real", body: "Afinações padrão, Drop D, DADGAD, abertas, GCEA e modo cromático, com cents, frequência, intensidade e estabilidade." }, { title: "Metrônomo flexível", body: "20–500 BPM, 1–12 tempos, Tap Tempo, subdivisões, swing, temporizadores e aumento progressivo de andamento. O flash traseiro pode marcar todos os tempos principais ou apenas os acentos, com três intensidades." }, { title: "Acordes interativos", body: "855 nomes por instrumento e 19.244 digitações no total; alterne, edite, identifique e ouça posições, e salve ou compartilhe o cartão atual." }],
  },
  {
    slug: "fr", htmlLang: "fr", title: "GuitarTool | Accordeur, métronome et accords", description: "Toutes les fonctions d’entraînement sont gratuites. Seuls les thèmes visuels optionnels sont payants, avec achat unique et accès permanent.", eyebrow: "TOUT POUR UNE PRATIQUE CONCENTRÉE", headline: "Accordez, gardez le tempo et trouvez vos accords hors ligne.", lead: "GuitarTool réunit un accordeur en temps réel, un métronome flexible et de riches bibliothèques d’accords de guitare et d’ukulélé dans une seule application claire.", download: "Télécharger gratuitement", trust: ["Outils essentiels hors ligne", "Sans publicité", "Sans compte"], versionUpdate: { label: "NOUVEAUTÉS DE LA VERSION 1.0.12", title: "Cinq thèmes premium transforment toute l’expérience.", body: "Toutes les fonctions d’entraînement sont gratuites ; seuls les thèmes visuels complets optionnels sont payants. Prévisualisez chaque thème sur tous les écrans avant l’achat. Chacun est un achat App Store unique et séparé, avec déblocage permanent et sans abonnement ; il fonctionne hors ligne après téléchargement et d’autres thèmes suivront." }, closing: "Prenez l’instrument et commencez : l’outil sait rester discret.",
    features: [{ title: "Accordeur en temps réel", body: "Accordages standard, Drop D, DADGAD, ouverts, GCEA et mode chromatique, avec cents, fréquence, niveau et stabilité." }, { title: "Métronome flexible", body: "20–500 BPM, 1 à 12 temps, Tap Tempo, subdivisions, swing, minuteries et accélération progressive. Le flash arrière peut marquer tous les temps principaux ou seulement les accents, avec trois intensités." }, { title: "Accords interactifs", body: "855 noms par instrument et 19 244 doigtés au total ; changez, modifiez, identifiez et écoutez les positions, puis enregistrez ou partagez la fiche actuelle." }],
  },
  {
    slug: "de", htmlLang: "de", title: "GuitarTool | Stimmgerät, Metronom & Akkorde", description: "Alle Übungsfunktionen sind kostenlos. Nur optionale Komplett-Themes kosten extra und werden per Einmalkauf dauerhaft freigeschaltet.", eyebrow: "ALLES FÜR KONZENTRIERTES ÜBEN", headline: "Stimmen, Tempo halten und Akkorde offline finden.", lead: "GuitarTool verbindet Echtzeit-Stimmgerät, flexibles Metronom und umfangreiche Akkordbibliotheken für Gitarre und Ukulele in einer ruhigen, klaren App.", download: "Kostenlos im App Store laden", trust: ["Kernwerkzeuge offline", "Keine Werbung", "Kein Konto"], versionUpdate: { label: "NEU IN VERSION 1.0.12", title: "Fünf Premium-Themes prägen das gesamte Erlebnis.", body: "Alle Übungsfunktionen sind kostenlos; nur optionale Komplett-Themes kosten extra. Sieh jedes Theme vor dem Kauf auf allen Seiten an. Jedes ist ein separater App Store-Einmalkauf mit dauerhafter Freischaltung und ohne Abo; nach dem Download funktioniert es offline, weitere Themes folgen." }, closing: "Instrument nehmen und anfangen – das Werkzeug bleibt im Hintergrund.",
    features: [{ title: "Echtzeit-Stimmgerät", body: "Standard-, Drop-D-, DADGAD-, offene und GCEA-Stimmungen sowie chromatischer Modus mit Cent-, Frequenz- und Stabilitätsanzeige." }, { title: "Flexibles Metronom", body: "20–500 BPM, 1–12 Schläge, Tap Tempo, Unterteilungen, Swing, Timer und schrittweise Tempoerhöhung. Der rückseitige Blitz kann alle Hauptschläge oder nur Akzente in drei Intensitäten markieren." }, { title: "Interaktive Akkorde", body: "Je 855 Akkordnamen und insgesamt 19.244 Griffe; Lagen wechseln, bearbeiten, erkennen und anhören sowie die aktuelle Griffkarte speichern oder teilen." }],
  },
  {
    slug: "it", htmlLang: "it", title: "GuitarTool | Accordatore, metronomo e accordi", description: "Tutte le funzioni di pratica sono gratuite. Solo i temi visivi opzionali sono a pagamento, con acquisto unico e sblocco permanente.", eyebrow: "TUTTO PER UNA PRATICA CONCENTRATA", headline: "Accorda, tieni il tempo e trova gli accordi offline.", lead: "GuitarTool unisce accordatore in tempo reale, metronomo flessibile e ampie librerie di accordi per chitarra e ukulele in un’unica app chiara e tranquilla.", download: "Scarica gratis su App Store", trust: ["Strumenti essenziali offline", "Senza pubblicità", "Senza account"], versionUpdate: { label: "NOVITÀ DELLA VERSIONE 1.0.12", title: "Cinque temi premium trasformano l’intera esperienza.", body: "Tutte le funzioni di pratica sono gratuite; solo i temi visivi completi opzionali sono a pagamento. Guarda ogni tema su tutte le schermate prima dell’acquisto. Ognuno è un acquisto App Store una tantum e separato, con sblocco permanente e senza abbonamento; funziona offline dopo il download e arriveranno altri temi." }, closing: "Prendi lo strumento e inizia: l’app lascia spazio alla musica.",
    features: [{ title: "Accordatore in tempo reale", body: "Accordature standard, Drop D, DADGAD, aperte, GCEA e modalità cromatica, con cents, frequenza, intensità e stabilità." }, { title: "Metronomo flessibile", body: "20–500 BPM, 1–12 movimenti, Tap Tempo, suddivisioni, swing, timer e aumento progressivo del tempo. Il flash posteriore può segnare tutti i battiti principali o solo gli accenti con tre intensità." }, { title: "Accordi interattivi", body: "855 nomi per strumento e 19.244 diteggiature totali; cambia, modifica, riconosci e ascolta le posizioni, poi salva o condividi la scheda attuale." }],
  },
  {
    slug: "ja", htmlLang: "ja", title: "GuitarTool｜チューナー・メトロノーム・コード", description: "練習機能はすべて無料で主要ツールはオフライン対応。オプションの完全ビジュアルテーマのみ有料で、1回購入すると永久に使えます。", eyebrow: "集中した練習に必要なすべて", headline: "チューニング、テンポ、コード確認をオフラインで。", lead: "GuitarToolはリアルタイムチューナー、柔軟なメトロノーム、ギターとウクレレの豊富なコードライブラリを、落ち着いた一つの流れにまとめます。", download: "App Storeで無料ダウンロード", trust: ["主要ツールはオフライン", "広告なし", "アカウント不要"], versionUpdate: { label: "バージョン1.0.12の新機能", title: "5種類の有料テーマが体験全体を変えます。", body: "練習機能はすべて無料で、オプションの完全ビジュアルテーマのみ有料です。購入前に各テーマをすべての画面でプレビューできます。各テーマはApp Storeで個別に1回購入すると永久にロック解除され、サブスクリプションはありません。ダウンロード後はオフライン対応。新テーマも継続追加予定です。" }, closing: "楽器を手に取ったら、すぐに練習を始められます。",
    features: [{ title: "リアルタイムチューナー", body: "標準、Drop D、DADGAD、オープン、GCEA、クロマチックに対応。セント、周波数、入力強度、安定度を表示します。" }, { title: "柔軟なメトロノーム", body: "20–500 BPM、1–12拍、タップテンポ、細分化、スウィング、タイマー、段階的テンポアップに対応。背面フラッシュはすべての主拍またはアクセントだけを3段階の強さで表示できます。" }, { title: "インタラクティブなコード", body: "各楽器855コード名、合計19,244種類の押さえ方。切替、編集、判定、試聴に加え、現在のコードカードを写真に保存・共有できます。" }],
  },
  {
    slug: "ko", htmlLang: "ko", title: "GuitarTool | 튜너, 메트로놈, 코드", description: "모든 연습 기능은 무료이고 핵심 도구는 오프라인으로 작동합니다. 선택형 완성 비주얼 테마만 유료이며 일회성 구매로 영구 해제됩니다.", eyebrow: "집중 연습에 필요한 모든 것", headline: "튜닝, 박자, 코드 찾기를 오프라인으로.", lead: "GuitarTool은 실시간 튜너, 유연한 메트로놈, 기타와 우쿨렐레 코드 라이브러리를 차분하고 명확한 하나의 흐름으로 연결합니다.", download: "App Store에서 무료 다운로드", trust: ["핵심 도구 오프라인", "광고 없음", "계정 불필요"], versionUpdate: { label: "버전 1.0.12의 새로운 기능", title: "유료 테마 5종이 전체 연습 경험을 바꿉니다.", body: "모든 연습 기능은 무료이며 선택형 완성 비주얼 테마만 유료입니다. 구매 전에 각 테마를 모든 화면에서 미리 볼 수 있습니다. 테마별 App Store 일회성 구매로 영구 잠금 해제되며 구독은 없습니다. 다운로드 후 오프라인에서 사용할 수 있고 새 테마도 계속 추가됩니다." }, closing: "악기를 들고 바로 시작하세요. 도구는 연습을 방해하지 않습니다.",
    features: [{ title: "실시간 튜너", body: "표준, Drop D, DADGAD, 오픈, GCEA 및 크로매틱 모드와 센트, 주파수, 입력 강도, 안정도 표시를 지원합니다." }, { title: "유연한 메트로놈", body: "20–500 BPM, 1–12박, 탭 템포, 세분음, 스윙, 타이머, 점진적 템포 증가를 제공합니다. 후면 플래시는 모든 주요 박자 또는 악센트만 세 단계 밝기로 표시할 수 있습니다." }, { title: "인터랙티브 코드", body: "악기별 855개 코드 이름과 총 19,244개 운지. 포지션을 바꾸고 편집·인식·재생한 뒤 현재 코드 카드를 사진에 저장하거나 공유할 수 있습니다." }],
  },
  {
    slug: "ru", htmlLang: "ru", title: "GuitarTool | Тюнер, метроном и аккорды", description: "Все функции для занятий бесплатны, основные инструменты работают офлайн. Платными являются только дополнительные полные визуальные темы.", eyebrow: "ВСЁ ДЛЯ СОСРЕДОТОЧЕННОЙ ПРАКТИКИ", headline: "Настройка, ритм и аккорды доступны офлайн.", lead: "GuitarTool объединяет тюнер реального времени, гибкий метроном и большие библиотеки аккордов для гитары и укулеле в одном спокойном приложении.", download: "Скачать бесплатно в App Store", trust: ["Основные инструменты офлайн", "Без рекламы", "Без аккаунта"], versionUpdate: { label: "НОВОЕ В ВЕРСИИ 1.0.12", title: "Пять премиум-тем меняют весь облик приложения.", body: "Все функции для занятий бесплатны; платными являются только дополнительные полные визуальные темы. Каждую тему можно просмотреть на всех экранах до покупки. Она открывается навсегда отдельной разовой покупкой в App Store, без подписки; после загрузки работает офлайн, а новые темы будут добавляться." }, closing: "Берите инструмент и начинайте — приложение не отвлекает от музыки.",
    features: [{ title: "Тюнер реального времени", body: "Стандартный строй, Drop D, DADGAD, открытые строи, GCEA и хроматический режим с центами, частотой и стабильностью." }, { title: "Гибкий метроном", body: "20–500 BPM, 1–12 долей, Tap Tempo, подразделения, свинг, таймеры и постепенное ускорение. Задняя вспышка может отмечать все основные доли или только акценты с тремя уровнями яркости." }, { title: "Интерактивные аккорды", body: "По 855 названий для каждого инструмента и 19 244 аппликатуры: меняйте, редактируйте, распознавайте и слушайте позиции, сохраняйте или отправляйте текущую карточку." }],
  },
  {
    slug: "tr", htmlLang: "tr", title: "GuitarTool | Akort, metronom ve akorlar", description: "Tüm çalışma özellikleri ücretsiz, temel araçlar çevrimdışı çalışır. Yalnızca isteğe bağlı tam görsel temalar ücretlidir.", eyebrow: "ODAKLI ÇALIŞMA İÇİN HER ŞEY", headline: "Akort et, tempoyu koru ve akorları çevrimdışı bul.", lead: "GuitarTool gerçek zamanlı akort cihazını, esnek metronomu ve kapsamlı gitar ile ukulele akor kitaplıklarını sakin ve net bir uygulamada birleştirir.", download: "App Store’dan ücretsiz indir", trust: ["Temel araçlar çevrimdışı", "Reklamsız", "Hesap gerektirmez"], versionUpdate: { label: "SÜRÜM 1.0.12 YENİLİKLERİ", title: "Beş premium tema tüm deneyimi dönüştürüyor.", body: "Tüm çalışma özellikleri ücretsizdir; yalnızca isteğe bağlı tam görsel temalar ücretlidir. Satın almadan önce her temayı tüm ekranlarda görün. Her biri App Store’dan ayrı, tek seferlik satın alımla kalıcı açılır; abonelik yoktur. İndirdikten sonra çevrimdışı çalışır ve yeni temalar eklenecektir." }, closing: "Enstrümanı elinize alın ve başlayın; araç müziğin önüne geçmez.",
    features: [{ title: "Gerçek zamanlı akort", body: "Standart, Drop D, DADGAD, açık, GCEA ve kromatik mod; cent, frekans, giriş gücü ve kararlılık göstergeleri." }, { title: "Esnek metronom", body: "20–500 BPM, 1–12 vuruş, Tap Tempo, alt bölümler, swing, zamanlayıcı ve kademeli tempo artışı. Arka flaş tüm ana vuruşları veya yalnızca aksanları üç yoğunlukta gösterebilir." }, { title: "Etkileşimli akorlar", body: "Her enstrüman için 855 ad ve toplam 19.244 pozisyon; değiştirin, düzenleyin, tanıyın ve dinleyin, ardından geçerli akor kartını kaydedin veya paylaşın." }],
  },
  {
    slug: "ar", htmlLang: "ar", dir: "rtl", title: "GuitarTool | موالف وميترونوم ومكتبة أوتار", description: "جميع ميزات التدريب مجانية، وتعمل الأدوات الأساسية بلا اتصال. المدفوع فقط هو السمات المرئية الكاملة الاختيارية.", eyebrow: "كل ما تحتاجه لتمرين مركّز", headline: "اضبط الآلة، حافظ على الإيقاع وابحث عن الأوتار دون اتصال.", lead: "يجمع GuitarTool موالفاً فورياً وميترونوماً مرناً ومكتبتين غنيتين لأوتار الغيتار واليوكليلي في تطبيق واحد واضح وهادئ.", download: "تنزيل مجاني من App Store", trust: ["الأدوات الأساسية بلا اتصال", "بلا إعلانات", "لا يحتاج إلى حساب"], versionUpdate: { label: "الجديد في الإصدار 1.0.12", title: "خمس سمات مدفوعة تغيّر تجربة التطبيق كاملة.", body: "جميع ميزات التدريب مجانية؛ المدفوع فقط هو السمات المرئية الكاملة الاختيارية. عاين كل سمة على جميع الشاشات قبل الشراء. تُفتح كل سمة دائمًا بشراء واحد مستقل عبر App Store، بلا اشتراك؛ تعمل دون اتصال بعد التنزيل وستُضاف سمات جديدة باستمرار." }, closing: "احمل آلتك وابدأ مباشرة؛ الأداة تترك المساحة للموسيقى.",
    features: [{ title: "موالف فوري", body: "يدعم الضبط القياسي وDrop D وDADGAD والضبط المفتوح وGCEA والوضع الكروماتي مع عرض السنت والتردد والثبات." }, { title: "ميترونوم مرن", body: "من 20 إلى 500 BPM، ومن 1 إلى 12 نبضة، وTap Tempo، وتقسيمات، وSwing، ومؤقتات وزيادة تدريجية للسرعة. ويمكن للفلاش الخلفي إظهار جميع النبضات الرئيسية أو النبرات فقط بثلاث درجات." }, { title: "أوتار تفاعلية", body: "855 اسماً لكل آلة و19,244 وضعية إجمالاً؛ بدّل وحرّر وتعرّف واستمع، ثم احفظ بطاقة الوضعية الحالية أو شاركها." }],
  },
];

export function getLocalePage(slug: string) { return localePages.find((page) => page.slug === slug); }
