export const enPracticePages = [
  {
    slug: "guitar-string-frequencies",
    title: "Guitar String Frequencies for Standard and Alternate Tunings",
    description: "Reference the exact frequencies for standard EADGBE, Drop D and half-step-down guitar tuning, then learn how cents and A4 calibration affect the target.",
    eyebrow: "GUITAR STRING FREQUENCIES",
    lead: "Use exact target frequencies as a reference, while remembering that a stable musical note matters more than chasing a flickering decimal.",
    proof: ["E2 82.41 Hz to E4 329.63 Hz", "Drop D and E-flat tables", "A4 = 440 Hz reference"],
    sections: [
      { title: "Standard EADGBE target frequencies", body: "From the sixth string to the first, standard guitar tuning at A4 = 440 Hz is E2 82.41 Hz, A2 110.00 Hz, D3 146.83 Hz, G3 196.00 Hz, B3 246.94 Hz and E4 329.63 Hz. Tune upward to the target when practical so the machine head settles under consistent tension.", points: ["E2 · 82.41 Hz", "A2 · 110.00 Hz", "D3 · 146.83 Hz", "G3 · 196.00 Hz", "B3 · 246.94 Hz", "E4 · 329.63 Hz"] },
      { title: "How alternate tuning changes the numbers", body: "Drop D changes only the sixth string to D2 73.42 Hz. Half-step-down tuning becomes E-flat2 77.78 Hz, A-flat2 103.83 Hz, D-flat3 138.59 Hz, G-flat3 185.00 Hz, B-flat3 233.08 Hz and E-flat4 311.13 Hz. A different A4 calibration shifts every target proportionally.", points: ["Drop D sixth string · 73.42 Hz", "One semitone equals 100 cents", "430–446 Hz calibration in the app"] },
    ],
    faq: [["What frequency is low E on guitar?", "E2 is approximately 82.41 Hz when A4 is calibrated to 440 Hz."], ["What frequency is Drop D?", "The lowered sixth string is D2 at approximately 73.42 Hz."], ["Why does the reading move after the attack?", "A plucked string begins with a complex transient and settles; use the stable sustain rather than the first instant."]],
    related: ["guitar-tuner", "chromatic-tuner", "half-step-down-tuning"],
  },
  {
    slug: "capo-transposition",
    title: "Guitar Capo Transposition Chart and Chord Guide",
    description: "Move familiar guitar chord shapes to a new key with a capo. Learn the semitone rule, common examples and how to name the chord that actually sounds.",
    eyebrow: "CAPO & CHORD TRANSPOSITION",
    lead: "Keep a familiar fingering under your hand while moving the sounding key upward one semitone for every capo fret.",
    proof: ["One fret = one semitone", "Shape name versus sounding chord", "Works with the interactive chord library"],
    sections: [
      { title: "Count semitones from the shape", body: "A capo raises every open string by the number of frets where it is placed. An open G shape with capo 2 sounds as A; C with capo 2 sounds as D; D with capo 2 sounds as E. With capo 3, G sounds as B-flat and C sounds as E-flat.", points: ["Capo 1 raises one semitone", "Capo 2 raises one whole step", "Capo 12 raises one octave"] },
      { title: "Choose shapes that make the progression playable", body: "Work backward from the required concert key. If a song is in E-flat but open E-flat shapes are awkward, capo 1 lets you play familiar D-family shapes. Check the lowest and highest notes as well as the chord names, because a capo also shortens the available range and changes the instrument's colour.", points: ["Concert E-flat · capo 1 · play D", "Concert B-flat · capo 3 · play G", "Concert F · capo 5 · play C"] },
    ],
    faq: [["Does a capo change chord shapes?", "Your fingering can stay the same, but the chord that sounds is raised by the capo fret count."], ["What does a G shape sound like with capo 2?", "It sounds as an A major chord."], ["Should I tune before or after adding the capo?", "Tune first, fit the capo close behind the fret without excess pressure, then check tuning again."]],
    related: ["guitar-chords", "guitar-tuner", "guitar-string-frequencies"],
  },
  {
    slug: "rhythm-practice",
    title: "Metronome Rhythm Practice: Build Speed Without Losing Control",
    description: "Use subdivisions, accents and progressive tempo steps to practise rhythm cleanly. Follow a repeatable metronome routine from slow accuracy to performance speed.",
    eyebrow: "RHYTHM PRACTICE ROUTINE",
    lead: "Speed is the result of repeatable, relaxed timing. Establish the motion slowly, then raise tempo only when the previous step remains clean.",
    proof: ["Start below failure tempo", "Raise BPM in small steps", "Use accents and subdivisions deliberately"],
    sections: [
      { title: "Find a tempo you can repeat cleanly", body: "Choose a BPM where the passage succeeds several times without extra tension. Practise short loops, align the difficult transition with a clear beat and listen for notes that consistently arrive early or late. A useful starting tempo is often 60–80% of the speed where control breaks down.", points: ["Loop one difficult transition", "Count subdivisions aloud", "Keep hands and shoulders relaxed"] },
      { title: "Increase speed with evidence, not hope", body: "After three clean repetitions, raise the metronome by 2–5 BPM. If timing or tone falls apart twice, step back rather than rehearsing the mistake. GuitarTool can automate the BPM increase after a chosen number of bars so attention stays on playing.", points: ["Three clean repetitions before moving", "Increase by 2–5 BPM", "Step back after repeated errors"] },
    ],
    faq: [["How fast should I increase the metronome?", "Two to five BPM is usually small enough to preserve the same motion."], ["Should the click mark every note?", "Not always. Start with enough subdivision to orient yourself, then reduce clicks to test internal pulse."], ["What if I tense up at the target tempo?", "Return to the fastest relaxed tempo and build again in smaller steps."]],
    related: ["online-metronome", "time-signatures", "offline-guitar-tools"],
  },
  {
    slug: "time-signatures",
    title: "Time Signatures for Guitar Practice: 4/4, 3/4, 6/8 and More",
    description: "Understand what common time signatures mean, how to count them and how to configure beats and subdivisions in a metronome.",
    eyebrow: "TIME SIGNATURES & COUNTING",
    lead: "The top number tells you how beats are grouped; the lower number tells you which written note represents the beat unit.",
    proof: ["Simple and compound meter", "Practical counting syllables", "Metronome setup examples"],
    sections: [
      { title: "Start with 4/4 and 3/4", body: "In 4/4, count four quarter-note beats: 1 2 3 4, often accenting beat 1. In 3/4, count 1 2 3 with a repeating three-beat shape. Eighth-note subdivisions can be counted 1-and-2-and so the hand keeps moving evenly between clicks.", points: ["4/4 · four quarter-note beats", "3/4 · three quarter-note beats", "Eighth notes · count numbers and ands"] },
      { title: "Feel 6/8 as two large beats", body: "Although 6/8 contains six written eighth notes, it is commonly felt as two dotted-quarter pulses: ONE-two-three FOUR-five-six. Set six beats with accents on 1 and 4 for detailed work, or use two main clicks with triplet subdivision when the larger motion is secure.", points: ["6/8 · two groups of three", "Accent written beats 1 and 4", "Move from six clicks to two pulses"] },
    ],
    faq: [["What does the bottom number mean?", "It identifies the written note value used as the unit: 4 means quarter note and 8 means eighth note."], ["Is 6/8 the same as 3/4?", "Both contain six eighth notes, but 6/8 usually groups them as two sets of three while 3/4 groups three sets of two."], ["Where should the metronome accent go?", "Begin with the first beat of each bar, then add structural accents such as beats 1 and 4 in 6/8."]],
    related: ["online-metronome", "rhythm-practice", "offline-guitar-tools"],
  },
];

export const zhPracticePages = [
  {
    slug: "guitar-string-frequencies",
    title: "吉他六根弦频率表：标准、Drop D 与降半音",
    description: "查看标准 EADGBE、Drop D 和降半音调弦的准确频率，并了解音分与 A4 校准如何影响目标音高。",
    eyebrow: "吉他琴弦频率参考",
    lead: "准确频率适合用来核对目标，但真正需要观察的是稳定延音，而不是追逐不断跳动的小数。",
    proof: ["E2 82.41 Hz 至 E4 329.63 Hz", "Drop D 与降半音频率", "以 A4 = 440 Hz 为基准"],
    sections: [
      { title: "标准 EADGBE 的六个目标频率", body: "以 A4 = 440 Hz 为基准，从第六弦到第一弦依次是 E2 82.41 Hz、A2 110.00 Hz、D3 146.83 Hz、G3 196.00 Hz、B3 246.94 Hz、E4 329.63 Hz。条件允许时从偏低位置向上调到目标，让弦钮在一致张力方向上稳定。", points: ["E2 · 82.41 Hz", "A2 · 110.00 Hz", "D3 · 146.83 Hz", "G3 · 196.00 Hz", "B3 · 246.94 Hz", "E4 · 329.63 Hz"] },
      { title: "特殊调弦如何改变数字", body: "Drop D 只把第六弦改为 D2 73.42 Hz。降半音则依次变为 E♭2 77.78 Hz、A♭2 103.83 Hz、D♭3 138.59 Hz、G♭3 185.00 Hz、B♭3 233.08 Hz、E♭4 311.13 Hz。改变 A4 校准会让全部目标按比例移动。", points: ["Drop D 第六弦 · 73.42 Hz", "一个半音等于 100 音分", "APP 支持 A4 430–446 Hz"] },
    ],
    faq: [["吉他低音 E 是多少 Hz？", "当 A4 = 440 Hz 时，E2 约为 82.41 Hz。"], ["Drop D 的最低弦是多少 Hz？", "降低后的第六弦是 D2，约 73.42 Hz。"], ["为什么拨弦后频率会移动？", "拨弦初始瞬态包含复杂泛音，应以随后较稳定的延音为准。"]],
    related: ["guitar-tuner", "chromatic-tuner", "half-step-down-tuning"],
  },
  {
    slug: "capo-transposition",
    title: "吉他变调夹移调表与和弦换算方法",
    description: "使用变调夹把熟悉的吉他和弦指法移动到新调：掌握每一品一个半音、指法名称与实际发声和弦的区别。",
    eyebrow: "变调夹与和弦移调",
    lead: "保持手中熟悉指法不变，变调夹每升高一品，实际发声调高一个半音。",
    proof: ["一品等于一个半音", "区分指法与实际和弦", "配合交互式和弦库"],
    sections: [
      { title: "从指法向上数半音", body: "变调夹会把全部空弦提高到所在品位。G 指法夹二品实际发声为 A，C 指法夹二品为 D，D 指法夹二品为 E；夹三品时，G 指法发声为 B♭，C 指法发声为 E♭。", points: ["夹一品提高一个半音", "夹二品提高一个全音", "夹十二品提高一个八度"] },
      { title: "反推最顺手的和弦指法", body: "先从歌曲实际调性反推。歌曲是 E♭、直接开放 E♭ 不顺手时，可以夹一品并弹 D 调指法。除了和弦名称，也要检查最低音和最高音，因为变调夹会缩短可用音域，并改变吉他的音色。", points: ["实际 E♭ · 夹一品 · 弹 D", "实际 B♭ · 夹三品 · 弹 G", "实际 F · 夹五品 · 弹 C"] },
    ],
    faq: [["变调夹会改变和弦指法吗？", "手型可以保持不变，但实际和弦会按变调夹品位整体升高。"], ["G 指法夹二品是什么和弦？", "实际发声是 A 大和弦。"], ["应该先调音还是先夹变调夹？", "先调音，再把变调夹贴近品丝并避免过大压力，最后重新检查音准。"]],
    related: ["guitar-chords", "guitar-tuner", "guitar-string-frequencies"],
  },
  {
    slug: "rhythm-practice",
    title: "节拍器节奏训练：在不失控的前提下提高速度",
    description: "用细分、重音和渐进加速建立稳定节奏；从慢速准确到目标速度，形成可以重复的节拍器练习流程。",
    eyebrow: "节拍与提速训练",
    lead: "速度来自可以反复复制的放松动作。先在慢速下建立正确轨迹，再在上一档保持干净时提高 BPM。",
    proof: ["从不会失败的速度开始", "小幅增加 BPM", "有目的地使用重音与细分"],
    sections: [
      { title: "找到可以稳定重复的起始速度", body: "选择一个能够连续完成、身体没有额外紧张的 BPM。把困难连接切成短循环，让关键动作对齐明确拍点，并留意哪些音总是提前或拖后。起始速度通常可以设为失去控制速度的 60–80%。", points: ["循环一个困难连接", "把细分数出声", "保持手腕与肩膀放松"] },
      { title: "用结果决定是否提速", body: "连续三次干净完成后，把节拍器提高 2–5 BPM。如果节奏或音色连续两次散掉，就先退回一档，避免把错误动作练熟。GuitarTool 可以按指定小节数自动提速，让注意力留在演奏上。", points: ["连续三次成功再前进", "每次提高 2–5 BPM", "重复失败时退回一档"] },
    ],
    faq: [["每次应该提高多少 BPM？", "2–5 BPM 通常足够小，能保留相同动作。"], ["节拍器需要点击每个音吗？", "不一定。开始时可以使用更多细分定位，稳定后减少点击来检查内在拍感。"], ["目标速度开始紧张怎么办？", "回到能够放松演奏的最高速度，再用更小步幅重新上升。"]],
    related: ["online-metronome", "time-signatures", "offline-guitar-tools"],
  },
  {
    slug: "time-signatures",
    title: "常见拍号练习：4/4、3/4、6/8 应该怎么数",
    description: "理解常见拍号的含义、数拍方式与节拍器设置方法，区分单拍子和复拍子，并正确安排重音与细分。",
    eyebrow: "拍号、数拍与重音",
    lead: "上方数字表示拍子如何分组，下方数字表示记谱中哪一种音符作为单位。",
    proof: ["单拍子与复拍子", "可直接使用的数拍方式", "对应节拍器设置"],
    sections: [
      { title: "先掌握 4/4 与 3/4", body: "4/4 每小节数四个四分音符拍：1 2 3 4，通常第一拍最重。3/4 则重复 1 2 3 的三拍结构。练八分音符时，可以数成 1-and-2-and，让手的运动在点击之间保持均匀。", points: ["4/4 · 四个四分音符拍", "3/4 · 三个四分音符拍", "八分音符 · 数数字与 and"] },
      { title: "把 6/8 感受成两个大拍", body: "6/8 虽然写有六个八分音符，通常应感受成两个附点四分音符大拍：一二三、四五六。细练时可设置六拍并重读 1、4，整体稳定后改成两个主点击并加入三连细分。", points: ["6/8 · 两组三个八分音符", "重读书写位置 1 与 4", "从六个点击过渡到两个大拍"] },
    ],
    faq: [["拍号下方数字表示什么？", "它表示作为记谱单位的音符：4 代表四分音符，8 代表八分音符。"], ["6/8 和 3/4 一样吗？", "两者都有六个八分音符，但 6/8 通常分成两组三个，3/4 则分成三组两个。"], ["节拍器重音应该放在哪里？", "先重读每小节第一拍，再按结构加入其他重音，例如 6/8 的第 1 与第 4 个八分音符。"]],
    related: ["online-metronome", "rhythm-practice", "offline-guitar-tools"],
  },
];
