import type { LandingPage } from "@/app/lib/landing-pages";

export const enTuningPages: LandingPage[] = [
  {
    slug: "drop-d-tuning",
    title: "Drop D Tuning Guide and Offline Tuner",
    description: "Tune guitar to Drop D (DADGBE) with an offline iPhone tuner. Learn the string notes, tune from standard and check every string with cents feedback.",
    eyebrow: "DROP D TUNING · D A D G B E",
    lead: "Lower the sixth string one whole step and keep the other five strings in standard tuning, with clear note, frequency and cents feedback.",
    proof: ["D A D G B E notes", "Automatic or locked-string tuning", "Works fully offline"],
    sections: [
      { title: "Move from standard tuning to Drop D", body: "Start from standard EADGBE, then lower only the thick sixth string from E2 to D2. The remaining strings stay A2, D3, G3, B3 and E4. In GuitarTool, select Drop D and work from the sixth string toward the first, letting the stability indicator settle before moving on.", points: ["Sixth string: E2 down to D2", "Strings 5–1 remain standard", "Cents and live frequency remain visible"] },
      { title: "Check the whole guitar, not only the low D", body: "Changing one string alters neck tension slightly, so recheck all six strings after the first pass. Drop D makes a D5 power chord available across the lowest three strings at one fret while keeping familiar shapes on the upper strings. The app can take you directly from tuning into chord lookup or tempo practice.", points: ["Second pass catches tension changes", "Reference tones support tuning by ear", "Continue into chords or the metronome"] },
    ],
    faq: [["What are the notes in Drop D tuning?", "From the thickest string to the thinnest: D2, A2, D3, G3, B3 and E4."], ["Do I retune every string for Drop D?", "No. Only the sixth string changes, moving from E2 down to D2."], ["Can GuitarTool tune Drop D without internet?", "Yes. Pitch detection and the Drop D target set run entirely on the device."]],
    related: ["guitar-tuner", "dadgad-tuning", "half-step-down-tuning"],
  },
  {
    slug: "dadgad-tuning",
    title: "DADGAD Tuning Guide and Offline Tuner",
    description: "Tune guitar to DADGAD with an offline tuner for iPhone and iPad. Follow the six target notes and verify cents, frequency and signal stability.",
    eyebrow: "DADGAD TUNING · D A D G A D",
    lead: "Set up the open, resonant DADGAD sound one string at a time without sending microphone audio off your device.",
    proof: ["D2 A2 D3 G3 A3 D4", "Per-string target locking", "Private on-device audio"],
    sections: [
      { title: "Reach DADGAD from standard tuning", body: "Beginning at standard EADGBE, lower the sixth string E2 to D2, keep A2, keep D3 and G3, lower B3 to A3, then lower the first string E4 to D4. Select the DADGAD preset so each target is explicit rather than relying only on the nearest chromatic note.", points: ["Lower strings 6, 2 and 1", "Keep strings 5, 4 and 3", "Lock a target when harmonics confuse detection"] },
      { title: "Let the changed tension settle", body: "Three lowered strings change the overall pull on the neck. Tune all six strings once, play a few open strums, then repeat the pass. The broad D and A resonance is useful for modal accompaniment, drones and fingerstyle, while the built-in metronome can keep repeating patterns even.", points: ["Tune twice after a large change", "Use input strength to avoid weak readings", "Practice patterns from 20–500 BPM"] },
    ],
    faq: [["What are the DADGAD string notes?", "From sixth to first string: D2, A2, D3, G3, A3 and D4."], ["Which strings change from standard tuning?", "Lower the sixth, second and first strings by one whole step; the other three stay unchanged."], ["Does the tuner support DADGAD offline?", "Yes. Select DADGAD and tune with on-device pitch analysis, without an account or network connection."]],
    related: ["guitar-tuner", "drop-d-tuning", "open-g-tuning"],
  },
  {
    slug: "open-g-tuning",
    title: "Open G Tuning Guide and Offline Tuner",
    description: "Tune guitar to Open G (DGDGBD) offline. See every target note, move safely from standard tuning and verify pitch with cents and stability feedback.",
    eyebrow: "OPEN G TUNING · D G D G B D",
    lead: "Retune to a complete G major sound across the open strings, then confirm the result with a second full pass.",
    proof: ["D G D G B D notes", "Open G preset", "No recording or upload"],
    sections: [
      { title: "Change three strings from standard", body: "From EADGBE, lower the sixth string E2 to D2, lower the fifth string A2 to G2, keep D3, G3 and B3, then lower the first string E4 to D4. The resulting D2 G2 D3 G3 B3 D4 notes spell a G major harmony across the open strings.", points: ["Lower strings 6, 5 and 1", "Keep strings 4, 3 and 2", "Use the preset to avoid octave mistakes"] },
      { title: "Recheck before playing with a slide", body: "Several lowered strings can pull the other strings slightly sharp, so repeat the tuning pass after a few strums. Open G supports movable major shapes and slide playing, but accurate intonation still depends on stable open-string tuning. GuitarTool shows cents, frequency, input strength and stability together.", points: ["Make a second pass after strumming", "Watch stability before accepting a note", "A4 calibration supports 430–446 Hz"] },
    ],
    faq: [["What are the notes for Open G tuning?", "From the sixth string to the first: D2, G2, D3, G3, B3 and D4."], ["Which strings stay the same as standard tuning?", "The fourth, third and second strings remain D3, G3 and B3."], ["Can I tune Open G without a connection?", "Yes. The Open G preset and pitch analysis work fully offline."]],
    related: ["guitar-tuner", "dadgad-tuning", "guitar-chords"],
  },
  {
    slug: "half-step-down-tuning",
    title: "Half-Step Down Guitar Tuning Guide",
    description: "Tune every guitar string down a semitone to Eb Ab Db Gb Bb Eb with a private offline tuner, cents display and 430–446 Hz calibration.",
    eyebrow: "HALF-STEP DOWN · E♭ A♭ D♭ G♭ B♭ E♭",
    lead: "Lower all six strings by one semitone while preserving the familiar intervals and chord shapes of standard tuning.",
    proof: ["E♭ A♭ D♭ G♭ B♭ E♭", "Flat-note targets", "Cents and frequency display"],
    sections: [
      { title: "Lower each string by one semitone", body: "Starting from standard tuning, the targets become E♭2, A♭2, D♭3, G♭3, B♭3 and E♭4. Work gradually across the neck rather than making large turns. GuitarTool's half-step-down preset keeps enharmonic labels clear and lets you lock onto the string you are adjusting.", points: ["All six strings move down equally", "Chord and scale shapes stay familiar", "Manual targets reduce adjacent-note confusion"] },
      { title: "Repeat the pass as tension changes", body: "Because every string is lowered, the first strings you tune may shift by the time you reach the other side. Make at least two passes and use the stability indicator before accepting each note. A softer overall tension can change playing feel, so finish by checking normal fretted notes and chord balance.", points: ["Use two or more tuning passes", "Avoid tuning only from a single chord", "Reference tones are available offline"] },
    ],
    faq: [["What are the half-step-down guitar notes?", "From sixth to first: E♭2, A♭2, D♭3, G♭3, B♭3 and E♭4."], ["Do standard chord shapes still work?", "Yes. The interval pattern is unchanged, but every sounding note is one semitone lower."], ["Is half-step-down tuning built into GuitarTool?", "Yes. Choose the preset and tune each target with offline pitch detection."]],
    related: ["guitar-tuner", "drop-d-tuning", "chromatic-tuner"],
  },
  {
    slug: "chromatic-tuner",
    title: "Offline Chromatic Tuner for String Instruments",
    description: "Use an offline chromatic tuner on iPhone or iPad with note, cents, frequency, signal-strength and stability feedback for guitar and other strings.",
    eyebrow: "CHROMATIC TUNER · OFFLINE",
    lead: "See the nearest pitch without choosing a tuning first, or lock a known target when you need a more directed reading.",
    proof: ["Nearest-note detection", "430–446 Hz calibration", "Audio stays on device"],
    sections: [
      { title: "Choose automatic detection or a fixed target", body: "Chromatic mode identifies the nearest note across the supported range, which is useful for alternate tunings and instruments without a dedicated preset. When nearby overtones make the reading jump, switch to a target string or note and watch the cents value move toward zero.", points: ["Note name and octave", "Live frequency and cents offset", "Input-strength and stability guidance"] },
      { title: "Get a cleaner reading from the instrument", body: "Pluck one string at a time near its usual playing position, mute the remaining strings and let the first transient pass. A steady note produces a more useful reading than a hard attack. GuitarTool processes microphone input live and does not save a recording or send audio to a server.", points: ["Mute sympathetic strings", "Use a consistent, moderate attack", "No account, ads or audio upload"] },
    ],
    faq: [["What is a chromatic tuner?", "It detects the nearest note rather than limiting detection to the strings of one preset tuning."], ["What does zero cents mean?", "Zero cents means the detected pitch matches the selected equal-tempered target at the current A4 calibration."], ["Does GuitarTool upload microphone audio?", "No. Audio is analyzed in real time on the device and is neither stored nor transmitted."]],
    related: ["guitar-tuner", "ukulele-gcea-tuning", "offline-guitar-tools"],
  },
  {
    slug: "ukulele-gcea-tuning",
    title: "Ukulele GCEA Tuning: High G and Low G",
    description: "Tune ukulele to High-G or Low-G GCEA with an offline iPhone tuner. Learn the octave difference and verify each string with cents feedback.",
    eyebrow: "UKULELE GCEA · HIGH G & LOW G",
    lead: "Keep C, E and A the same, then choose the re-entrant high G or linear low G that matches your instrument and strings.",
    proof: ["High-G G4 C4 E4 A4", "Low-G G3 C4 E4 A4", "Dedicated GCEA targets"],
    sections: [
      { title: "Know which G string is installed", body: "Standard high-G tuning is G4 C4 E4 A4, with the first G pitched above middle C. Low-G tuning uses G3 C4 E4 A4, placing the notes in ascending order. The C, E and A targets do not change; only the octave and suitable string for G are different.", points: ["High G is re-entrant", "Low G creates a linear range", "Choose the preset that matches the string"] },
      { title: "Tune four strings with stable feedback", body: "Select the correct GCEA mode, pluck one string while muting the others and wait for the stability indicator before moving on. After the first pass, repeat all four strings because tension changes can shift earlier readings. The app also includes a separate 6,829-fingering ukulele chord library.", points: ["Automatic or locked-string mode", "A4 calibration from 430–446 Hz", "Continue into 855 ukulele chord names"] },
    ],
    faq: [["What are the standard ukulele tuning notes?", "High-G standard tuning is G4, C4, E4 and A4."], ["What changes in Low-G tuning?", "Only the G string moves down an octave, from G4 to G3; C4, E4 and A4 stay the same."], ["Can GuitarTool tune both High G and Low G?", "Yes. Both GCEA target sets are available and work entirely offline."]],
    related: ["ukulele-tuner", "ukulele-chords", "chromatic-tuner"],
  },
];

export const zhTuningPages: LandingPage[] = [
  {
    slug: "drop-d-tuning",
    title: "Drop D 调弦方法与离线调音器",
    description: "把吉他调成 Drop D（DADGBE）：了解六根弦目标音，从标准调弦快速切换，并用离线调音器检查音分与稳定度。",
    eyebrow: "DROP D 调弦 · D A D G B E",
    lead: "只把第六弦从 E 降到 D，另外五根弦保持标准调弦，并用音分、频率与稳定度确认结果。",
    proof: ["D A D G B E 六弦音名", "自动识别或手动锁弦", "完全离线运行"],
    sections: [
      { title: "从标准调弦切换到 Drop D", body: "先保持标准 EADGBE，只把最粗的第六弦从 E2 降一个全音到 D2；其余仍为 A2、D3、G3、B3、E4。在 GuitarTool 中选择 Drop D，从第六弦依次检查到第一弦，每根弦稳定后再继续。", points: ["第六弦 E2 降至 D2", "第 5–1 弦保持标准", "同时查看音分与实时频率"] },
      { title: "不要只检查最低的 D", body: "一根弦张力变化后，其他弦的读数也可能轻微移动，因此第一次调完要再完整检查一遍。Drop D 可以在最低三根弦上用同一品位形成 D5 强力和弦，上方琴弦仍保留熟悉的标准关系。", points: ["第二遍检查张力变化", "可播放参考音辅助听觉调弦", "调完直接进入和弦库或节拍器"] },
    ],
    faq: [["Drop D 六根弦分别是什么音？", "从最粗到最细依次是 D2、A2、D3、G3、B3、E4。"], ["Drop D 需要调整所有弦吗？", "不需要，只把第六弦从 E2 降到 D2。"], ["没有网络可以使用吗？", "可以，Drop D 目标音与音高检测全部在设备端离线运行。"]],
    related: ["guitar-tuner", "dadgad-tuning", "half-step-down-tuning"],
  },
  {
    slug: "dadgad-tuning",
    title: "DADGAD 调弦方法与离线调音器",
    description: "把吉他调成 DADGAD：按 D2 A2 D3 G3 A3 D4 逐弦检查，使用 iPhone 与 iPad 离线调音器确认音分和稳定度。",
    eyebrow: "DADGAD 调弦 · D A D G A D",
    lead: "按六个明确目标音完成开放、共鸣丰富的 DADGAD 调弦，麦克风声音不会离开设备。",
    proof: ["D2 A2 D3 G3 A3 D4", "支持逐弦锁定目标", "声音只在设备端处理"],
    sections: [
      { title: "从标准调弦到 DADGAD", body: "从 EADGBE 开始，把第六弦 E2 降至 D2；第五弦保持 A2，第四弦保持 D3，第三弦保持 G3；第二弦 B3 降至 A3，第一弦 E4 降至 D4。选择 DADGAD 预设后，每根弦的目标会比单纯依赖最近音识别更明确。", points: ["降低第 6、2、1 弦", "第 5、4、3 弦保持不变", "泛音干扰时可手动锁定目标"] },
      { title: "让变化后的张力先稳定", body: "三根弦同时降低会改变整体张力。完整调一遍后，先弹几次空弦，再重复检查六根弦。D 与 A 的持续共鸣适合开放伴奏、Drone 与指弹，内置节拍器则能帮助重复型保持均匀。", points: ["大幅换调后至少检查两遍", "用输入强度避免过弱读数", "可用 20–500 BPM 练习型节拍器"] },
    ],
    faq: [["DADGAD 六根弦是什么音？", "从第六弦到第一弦依次为 D2、A2、D3、G3、A3、D4。"], ["从标准调弦需要改哪几根弦？", "第六、第二和第一弦各降低一个全音，另外三根不变。"], ["调音器可以离线识别 DADGAD 吗？", "可以，选择 DADGAD 后无需账户和网络即可完成设备端检测。"]],
    related: ["guitar-tuner", "drop-d-tuning", "open-g-tuning"],
  },
  {
    slug: "open-g-tuning",
    title: "Open G 开放 G 调弦方法",
    description: "把吉他离线调成 Open G（DGDGBD）：查看六根弦目标音、从标准调弦安全切换，并用音分与稳定度确认音准。",
    eyebrow: "OPEN G 调弦 · D G D G B D",
    lead: "让六根空弦共同组成 G 大调和声，调完后再完整复查一次，获得更稳定的开放调弦。",
    proof: ["D G D G B D 六弦音名", "内置 Open G 预设", "不保存或上传录音"],
    sections: [
      { title: "从标准调弦改变三根弦", body: "从 EADGBE 出发，把第六弦 E2 降到 D2，第五弦 A2 降到 G2；第四、第三、第二弦保持 D3、G3、B3；最后把第一弦 E4 降到 D4。得到的 D2 G2 D3 G3 B3 D4 在空弦状态组成 G 大调和声。", points: ["降低第 6、5、1 弦", "第 4、3、2 弦保持不变", "用预设避免把音调错八度"] },
      { title: "滑棒演奏前先复查", body: "多根弦降低后，其他弦可能被张力变化轻微带高，因此空弦扫几次后再调第二遍。Open G 适合移动式大和弦和滑棒演奏，而可靠音准仍要从稳定的空弦开始。GuitarTool 会同时显示音分、频率、输入强度与稳定度。", points: ["扫弦后进行第二遍检查", "稳定度足够后再接受读数", "A4 支持 430–446 Hz 校准"] },
    ],
    faq: [["Open G 六根弦是什么音？", "从第六弦到第一弦是 D2、G2、D3、G3、B3、D4。"], ["哪些弦与标准调弦相同？", "第四、第三、第二弦仍为 D3、G3、B3。"], ["Open G 可以完全离线调吗？", "可以，Open G 预设与音高分析都不依赖网络。"]],
    related: ["guitar-tuner", "dadgad-tuning", "guitar-chords"],
  },
  {
    slug: "half-step-down-tuning",
    title: "吉他降半音调弦方法",
    description: "把六根吉他弦全部降半音至 E♭ A♭ D♭ G♭ B♭ E♭，使用离线调音器查看音分、频率与稳定度。",
    eyebrow: "降半音调弦 · E♭ A♭ D♭ G♭ B♭ E♭",
    lead: "六根弦统一降低一个半音，保留标准调弦的音程关系与熟悉指法。",
    proof: ["E♭ A♭ D♭ G♭ B♭ E♭", "清楚显示降号目标音", "音分与频率反馈"],
    sections: [
      { title: "每根弦降低一个半音", body: "从标准调弦开始，六根弦目标依次变为 E♭2、A♭2、D♭3、G♭3、B♭3、E♭4。逐步转动弦钮，不要一次跨过目标。GuitarTool 的降半音预设会清楚显示等音名称，也可以锁定正在调整的琴弦。", points: ["六根弦降低相同距离", "和弦与音阶指法保持原样", "手动目标减少相邻音干扰"] },
      { title: "张力改变后至少再调一遍", body: "所有弦一起降低时，最先调好的琴弦可能在到达另一侧后再次偏移。建议完整检查两遍以上，每根弦稳定后再继续。整体张力变软也会影响手感，最后可弹奏常用和弦确认各弦平衡。", points: ["进行两遍或更多完整检查", "不要只通过一个和弦判断", "参考音同样支持离线播放"] },
    ],
    faq: [["吉他降半音的六个音是什么？", "从第六弦到第一弦为 E♭2、A♭2、D♭3、G♭3、B♭3、E♭4。"], ["标准和弦指法还能使用吗？", "可以，音程关系不变，但实际声音整体降低一个半音。"], ["GuitarTool 内置降半音吗？", "内置，选择预设后可用离线音高检测逐弦完成。"]],
    related: ["guitar-tuner", "drop-d-tuning", "chromatic-tuner"],
  },
  {
    slug: "chromatic-tuner",
    title: "离线十二平均律调音器",
    description: "iPhone 与 iPad 离线十二平均律调音器：显示最近音名、音分、频率、输入强度和稳定度，适合吉他与多种弦乐器。",
    eyebrow: "十二平均律调音器 · 完全离线",
    lead: "不选择固定调弦也能识别最近音高；已知目标时，则可以锁定音符获得更明确的反馈。",
    proof: ["自动识别最近音", "A4 430–446 Hz 校准", "声音不会离开设备"],
    sections: [
      { title: "自动识别与固定目标如何选择", body: "十二平均律模式会显示检测到的最近音，适合特殊调弦和没有专属预设的弦乐器。如果相邻泛音让读数跳动，可以切换到目标琴弦或音符，再观察音分逐渐靠近零。", points: ["显示音名与八度", "实时频率与音分偏差", "输入强度和稳定度辅助判断"] },
      { title: "让乐器给出更干净的读数", body: "一次只拨一根弦，同时压住其他弦的共振，使用正常力度并让最初的强烈瞬态过去。稳定延音比过重拨弦更容易判断。GuitarTool 只实时分析麦克风输入，不保存录音，也不会把声音发往服务器。", points: ["抑制其他琴弦共振", "保持一致且适中的拨弦力度", "无需账户、广告与音频上传"] },
    ],
    faq: [["什么是十二平均律调音器？", "它不局限于某个预设的琴弦，而是识别当前音高最接近的十二平均律音符。"], ["音分为零表示什么？", "表示在当前 A4 校准下，检测音高与选定目标相符。"], ["麦克风声音会上传吗？", "不会，声音只在设备端实时分析，不保存也不传输。"]],
    related: ["guitar-tuner", "ukulele-gcea-tuning", "offline-guitar-tools"],
  },
  {
    slug: "ukulele-gcea-tuning",
    title: "尤克里里 GCEA 调弦：High G 与 Low G",
    description: "用离线调音器完成尤克里里 High-G 或 Low-G GCEA 调弦，了解 G 弦的八度差异，并逐弦检查音分与稳定度。",
    eyebrow: "尤克里里 GCEA · HIGH G 与 LOW G",
    lead: "C、E、A 三根弦保持相同，根据乐器上的 G 弦选择回入式 High G 或线性的 Low G。",
    proof: ["High-G：G4 C4 E4 A4", "Low-G：G3 C4 E4 A4", "专用 GCEA 目标音"],
    sections: [
      { title: "先确认安装的是哪一种 G 弦", body: "标准 High-G 是 G4、C4、E4、A4，第一根 G 的音高位于中央 C 之上，形成回入式顺序。Low-G 是 G3、C4、E4、A4，四根弦按音高依次上升。C、E、A 不变，区别只在 G 的八度与适用琴弦。", points: ["High G 属于回入式调弦", "Low G 提供连续的线性音域", "预设必须与实际 G 弦匹配"] },
      { title: "用稳定反馈完成四根弦", body: "选择对应 GCEA 模式，一次拨一根弦并抑制其他弦的共振，稳定度足够后再继续。第一遍完成后重复检查四根弦，因为张力变化可能让早先读数移动。APP 还包含独立的 6,829 个尤克里里指法。", points: ["自动识别或手动锁弦", "A4 支持 430–446 Hz 校准", "调完可继续查询 855 个和弦名称"] },
    ],
    faq: [["标准尤克里里调弦是什么音？", "High-G 标准调弦是 G4、C4、E4、A4。"], ["Low-G 改变了什么？", "只有 G 弦从 G4 降低一个八度到 G3，C4、E4、A4 不变。"], ["GuitarTool 同时支持 High G 和 Low G 吗？", "支持，两套 GCEA 目标都可以完全离线使用。"]],
    related: ["ukulele-tuner", "ukulele-chords", "chromatic-tuner"],
  },
];
